name: check site build
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - run: sbt 'project axle-docs' clean
      - run: sbt 'project axle-docs' mdoc
      - run: sbt 'project axle-docs' laikaSite
