name: site
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - run: sbt -J-Xmx8G 'project axle-docs' clean mdoc laikaSite
